[tool.ruff]
exclude = [
    "migrations",
    "__pycache__",
    "venv",
]

[tool.ruff.lint]
select = ["TID252", "F", "W", "I"]

[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["F401"]

[tool.ruff.lint.flake8-tidy-imports]
ban-relative-imports = "all"

[tool.ruff.lint.isort]
length-sort=true
no-lines-before=["local-folder"]
default-section = "first-party"
section-order = ["future", "standard-library", "third-party", "first-party", "local-folder"]
known-first-party = ['app']
known-third-party = ['django']
